// Generated by CoffeeScript 1.6.1
(function() {
  var $, contextable;

  $ = jQuery;

  contextable = function(menu) {
    var $el, $menu, createMenu, destroyMenu;
    if (menu == null) {
      throw new Error("Contextable - `menu` must be an object.");
    }
    $el = $(this);
    $menu = $('<ul class="contextable-menu"></ul>');
    $el.on('contextmenu', function(ev) {
      ev.preventDefault();
      ev.stopPropagation();
      if (ev.which === 3) {
        if ($el.data('menu')) {
          destroyMenu();
        }
        createMenu(ev);
        return $el.data('menu', true);
      }
    });
    createMenu = function(ev) {
      var $item, item, _i, _len;
      for (_i = 0, _len = menu.length; _i < _len; _i++) {
        item = menu[_i];
        $item = $("<li class='contextable-item'>" + item.html + "</li>");
        $item.data('fn', item.handler);
        $item.click(function(e) {
          var fn;
          fn = $(e.target).data('fn');
          return fn(e, ev);
        });
        $menu.append($item);
      }
      $menu.css({
        top: ev.pageY,
        left: ev.pageX
      });
      $("body").append($menu);
      return $(document).on('click', 'html', function(e) {
        return destroyMenu();
      });
    };
    return destroyMenu = function() {
      $menu.remove();
      $menu = $('<ul class="contextable-menu"></ul>');
      $el.data('menu', false);
      return $(document).off('click', 'html');
    };
  };

  $.fn.extend({
    contextable: contextable
  });

  $.fn.contextable = contextable;

}).call(this);
